---
title: "Package Check EDA"
author: "Willem van der Schans"
date: "2/13/2021"
output:
  html_document: default
  pdf_document: default
---

```{r, echo=F, message=FALSE, warning=FALSE}
# Base Packages
library(dplyr) # Additional Base level functionality of R 
library(stats) # Base Statistic Funtionality

# Extended Base Functionality
library(reshape2) # Melt Function Correlation Matrix
library(rlist) #list.append
library(lubridate) # For working with dates
library(caret) # MachineLearning package used for createDataPartition

# Visualisation Packages
library(ggplot2) # Comprehensive Graphical Output Package 
library(ggthemes) # More themes for GGPLOT2
library(scales) # Control over Axis formatting
library(gghighlight) # GGplot Highlight function
library(gridExtra) # Plot in Grids

# Latex Packages
library(xtable) # Latex Tables
library(papeR) # Paper Writing Module
library(reporttools) # Latex Sumarry Tables
```

```{r}
download.file("https://raw.githubusercontent.com/Kydoimos97/CapstoneMSBA2020/main/EDA/Main_EDA.Rmd", "Main_EDA_DL.Rmd")

knitr::purl("Main_EDA_DL.Rmd", quiet=TRUE)

NCmisc::list.functions.in.file("Main_EDA_DL.R")
```

